### ISSUE TITLE
[Bug] FNLU GroundRadar Stand Labels Update

### ISSUE THREAD

**Issue by miguelalbano** [VATSIM-SSA/sectorfile-fnan#3]
![image](https://github.com/VATSIM-SSA/sectorfile-fnan/assets/30835922/6dd3b4bd-b4ac-4527-9832-08247546603b)
![image-1](https://github.com/VATSIM-SSA/sectorfile-fnan/assets/30835922/6f757389-b54f-4277-a4a3-c3f552d2345b)

**Comment by RoboFun01** [comment]
Roger, I will definately give this a try!

**Comment by RoboFun01** [comment]
@miguelalbano When you are able, can you please convert and add these paths to the .sct file in GnG. Is it for stands A1-A6 which isn't currently in the sector files. I will add the GroundRadar data for it so long.
[FNLU Stands SCT Additions.zip](https://github.com/user-attachments/files/16786960/FNLU.Stands.SCT.Additions.zip)
